version: '3'

services:
  bot:
    container_name: poop-bot
    build:
      context: .
      args:
        - POSTGRES_HOST=db
      dockerfile: ./apps/bot/Dockerfile
    restart: unless-stopped
    env_file:
      - ./apps/bot/.env
    ports:
      - 3000:3000
    depends_on:
      - db
  #   networks:
  #     - bot_network

  db:
    image: postgres:14-alpine
    container_name: bot-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db-data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # networks:
    #   - bot_network

  adminer:
    image: adminer
    container_name: bot-db-admin
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - db
    # networks:
    #   - bot_network
# networks:
#   bot_network:
#     external: true
